name: spconv_unet
dataset: semanticbridge
collator: voxel
ending: .ply
loops: 1
voxel_size: 0.08
data_dir: /data/dataset/
save_dir: results/spconv_unet_bridge
apply_transform: True
bound:
  - 3
  - 3
  - 3
train:
  bs: 2
  lr: 0.001
  mom: 0.9
  wd: 0.0001
  ep: 800
  gamma: 0.98
model:
  in_channels: 6
  num_classes: 9
  enc_channels:
    - 32
    - 64
    - 128
    - 256